version: '3'
services:
  web:
    container_name: caption-this
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file: .env
    ports:
      - "80:$PORT"