version: '3'
services:
  web:
    container_name: caption-this
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # You will need this for the nodemon
      - ./:/usr/src/app
    #  - exclude:/usr/src/app/node_modules
    env_file: .env
    ports:
      - "$PORT:$PORT"